@url = {{BASE_URL}}/storage
@analysis_id = 01KSZX2Z0S0MBNPTF7VNHJKP95

### Gerar URL de upload para documento PDF (GenerateAnalysisDocumentUploadUrlController)
POST {{url}}/analyses/{{analysis_id}}/documents?document_type=pdf
Authorization: Bearer {{ACCESS_TOKEN}}

### Gerar URL de upload para documento DOCX (GenerateAnalysisDocumentUploadUrlController)
POST {{url}}/analyses/{{analysis_id}}/documents?document_type=docx
Authorization: Bearer {{ACCESS_TOKEN}}

