@url = {{BASE_URL}}/auth
@name = Usuario Teste
@email = animus.ctrlaltdel@gmail.com
@password = Senha@123
@otp = 583108
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMUtNWDNTQlowRjU1UlE3WDY5V1lFRlo3SyIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzgwMTAyODg3LCJleHAiOjE3ODAxODkyODd9.kzEIruYTbKd0SZ6FA6daXYan4Ch-KomQ70klQW4yn6c

### Entrar com email e senha (SignInController)
POST {{url}}/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Criar conta (SignUpController)
POST {{url}}/sign-up
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Reenviar email de verificacao (ResendVerificationEmailController)
POST {{url}}/resend-verification-email
Content-Type: application/json

{
  "email": "{{email}}"
}

### Verificar email com OTP (VerifyEmailController)
POST {{url}}/verify-email
Content-Type: application/json

{
  "email": "{{email}}",
  "otp": "{{otp}}"
}

### Renovar sessao com refresh token (RefreshSessionController)
POST {{url}}/refresh
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}
