###
@url = {{BASE_URL}}/auth
@name = Usuario Teste
@email = animus.ctrlaltdel@gmail.com
@password = Senha@123
@otp = 583108

### Entrar com email e senha (SignInController)
POST {{url}}/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Criar conta (SignUpController)
POST {{url}}/sign-up
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Reenviar email de verificacao (ResendVerificationEmailController)
POST {{url}}/resend-verification-email
Content-Type: application/json

{
  "email": "{{email}}"
}

### Verificar email com OTP (VerifyEmailController)
POST {{url}}/verify-email
Content-Type: application/json

{
  "email": "{{email}}",
  "otp": "{{otp}}"
}

