###
@url = {{BASE_URL}}/auth
@name = Usuario Teste
@email = joaopcarvalho.cds@gmail.com
@password = Senha@123
@otp = 583108

### Criar conta (SignUpController)
POST {{url}}/sign-up
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Reenviar email de verificacao (ResendVerificationEmailController)
POST {{url}}/resend-verification-email
Content-Type: application/json

{
  "email": "{{email}}"
}

### Verificar email com OTP (VerifyEmailController)
POST {{url}}/verify-email
Content-Type: application/json

{
  "email": "{{email}}",
  "otp": "{{otp}}"
}

### Entrar com email e senha (SignInController)
POST {{url}}/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### teste 
POST https://pangeabnp.pdpj.jus.br/api/v1/precedentes
Content-Type: application/json 

{
"filtro": {
    "ordenacao": "Text",
    "orgaos": [
      "TRT18",
      "TJPA"
    ],
    "pagina": 1,
    "tipos": [
      "IRDR",
      "IAC"
    ]
  }
}
