from enum import StrEnum


class FirstInstanceAnalysisStatus(StrEnum):
    WAITING_DOCUMENT_UPLOAD = 'WAITING_DOCUMENT_UPLOAD'
    DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED'
    ANALYZING_CASE = 'ANALYZING_CASE'
    CASE_ANALYZED = 'CASE_ANALYZED'
    SEARCHING_PRECEDENTS = 'SEARCHING_PRECEDENTS'
    ANALYZING_PRECEDENTS_SIMILARITY = 'ANALYZING_PRECEDENTS_SIMILARITY'
    ANALYZING_PRECEDENTS_APPLICABILITY = 'ANALYZING_PRECEDENTS_APPLICABILITY'
    DONE = 'DONE'
    FAILED = 'FAILED'

    @classmethod
    def get_processing_statuses(cls) -> tuple['FirstInstanceAnalysisStatus', ...]:
        return (
            cls.ANALYZING_CASE,
            cls.SEARCHING_PRECEDENTS,
            cls.ANALYZING_PRECEDENTS_SIMILARITY,
            cls.ANALYZING_PRECEDENTS_APPLICABILITY,
        )
