from enum import StrEnum


class SecondInstanceAnalysisStatus(StrEnum):
    WAITING_DOCUMENT_UPLOAD = 'WAITING_DOCUMENT_UPLOAD'
    DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED'
    EXTRACTING_PETITION = 'EXTRACTING_PETITION'
    ANALYZING_CASE = 'ANALYZING_CASE'
    CASE_ANALYZED = 'CASE_ANALYZED'
    SEARCHING_PRECEDENTS = 'SEARCHING_PRECEDENTS'
    ANALYZING_PRECEDENTS_SIMILARITY = 'ANALYZING_PRECEDENTS_SIMILARITY'
    ANALYZING_PRECEDENTS_APPLICABILITY = 'ANALYZING_PRECEDENTS_APPLICABILITY'
    GENERATING_JUDGMENT_DRAFT = 'GENERATING_JUDGMENT_DRAFT'
    DONE = 'DONE'
    PETITION_NOT_FOUND = 'PETITION_NOT_FOUND'
    FAILED = 'FAILED'

    @classmethod
    def get_processing_statuses(cls) -> tuple['SecondInstanceAnalysisStatus', ...]:
        return (
            cls.EXTRACTING_PETITION,
            cls.ANALYZING_CASE,
            cls.SEARCHING_PRECEDENTS,
            cls.ANALYZING_PRECEDENTS_APPLICABILITY,
            cls.ANALYZING_PRECEDENTS_SIMILARITY,
            cls.GENERATING_JUDGMENT_DRAFT,
        )
