"""drop analysis summary column

Revision ID: 4249bef21384
Revises: d6394e173b37
Create Date: 2026-03-27 14:39:41.004653

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4249bef21384'
down_revision: str | Sequence[str] | None = 'd6394e173b37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
