"""head

Revision ID: 4ab74425d1ee
Revises: 20260330_120000
Create Date: 2026-04-04 01:23:05.859794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab74425d1ee'
down_revision: Union[str, Sequence[str], None] = '20260330_120000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('folder_id', sa.String(length=26), nullable=True),
    sa.Column('account_id', sa.String(length=26), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_account_id'), 'analyses', ['account_id'], unique=False)
    op.create_table('petitions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('analysis_id', sa.String(length=26), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document_file_path', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_petitions_analysis_id'), 'petitions', ['analysis_id'], unique=False)
    op.create_table('analysis_precedents',
    sa.Column('analysis_id', sa.String(length=26), nullable=False),
    sa.Column('precedent_id', sa.String(length=26), nullable=False),
    sa.Column('is_chosen', sa.Boolean(), nullable=False),
    sa.Column('applicability_percentage', sa.Float(), nullable=True),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['precedent_id'], ['precedents.id'], ),
    sa.PrimaryKeyConstraint('analysis_id', 'precedent_id')
    )
    op.create_table('petition_summaries',
    sa.Column('petition_id', sa.String(length=26), nullable=False),
    sa.Column('case_summary', sa.Text(), nullable=False),
    sa.Column('legal_issue', sa.Text(), nullable=False),
    sa.Column('central_question', sa.Text(), nullable=False),
    sa.Column('relevant_laws', sa.JSON(), nullable=False),
    sa.Column('key_facts', sa.JSON(), nullable=False),
    sa.Column('search_terms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petition_id'], ['petitions.id'], ),
    sa.PrimaryKeyConstraint('petition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petition_summaries')
    op.drop_table('analysis_precedents')
    op.drop_index(op.f('ix_petitions_analysis_id'), table_name='petitions')
    op.drop_table('petitions')
    op.drop_index(op.f('ix_analyses_account_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
