"""make_password_hash_null

Revision ID: 665569c27179
Revises: a7076e5f1905
Create Date: 2026-03-24 09:13:18.927467

"""
from collections.abc import Sequence



# revision identifiers, used by Alembic.
revision: str = '665569c27179'
down_revision: str | Sequence[str] | None = 'a7076e5f1905'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
