"""""

Revision ID: a7076e5f1905
Revises: bb5751bdd2fd
Create Date: 2026-03-24 09:05:27.177312

"""
from collections.abc import Sequence



# revision identifiers, used by Alembic.
revision: str = 'a7076e5f1905'
down_revision: str | Sequence[str] | None = 'bb5751bdd2fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
