"""head

Revision ID: ee4204a91fe4
Revises: 8cb87a9d6608
Create Date: 2026-03-26 22:44:42.067111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4204a91fe4'
down_revision: Union[str, Sequence[str], None] = '8cb87a9d6608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('precedents',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('court', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('enunciation', sa.Text(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('last_updated_in_pangea_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court', 'kind', 'number', name='uq_precedent_identifier')
    )
    op.create_index(op.f('ix_precedents_court'), 'precedents', ['court'], unique=False)
    op.create_index(op.f('ix_precedents_kind'), 'precedents', ['kind'], unique=False)
    op.create_index(op.f('ix_precedents_number'), 'precedents', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_precedents_number'), table_name='precedents')
    op.drop_index(op.f('ix_precedents_kind'), table_name='precedents')
    op.drop_index(op.f('ix_precedents_court'), table_name='precedents')
    op.drop_table('precedents')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
