from typing import Protocol

from animus.core.auth.domain.entities import Account
from animus.core.auth.domain.structures.email import Email
from animus.core.shared.domain.structures import Id, Text


class AccountsRepository(Protocol):
    def find_by_id(self, account_id: Id) -> Account: ...

    def find_by_email(self, email: Email) -> Account: ...

    def find_password_hash_by_email(self, email: Email) -> Text | None: ...

    def add(self, account: Account, password_hash: Text | None) -> None: ...

    def add_many(self, accounts: list[tuple[Account, Text | None]]) -> None: ...

    def replace(self, account: Account) -> None: ...
