from typing import Protocol

from animus.core.shared.domain.structures import Text, Ttl


class CacheProvider(Protocol):
    def get(self, key: str) -> Text | None: ...

    def set(self, key: str, value: Text) -> None: ...

    def set_with_ttl(self, key: str, value: Text, ttl: Ttl) -> None: ...

    def delete(self, key: str) -> None: ...
