@url = {{BASE_URL}}/intake
@analysis_id = 01KMQTN9YCHWG20ZZEPNBRYW87
@uploaded_at = 2026-03-27T12:00:00Z
@file_path = intake/analises/{{analysis_id}}/petitions/Ação Cobrança Lei 12855 Tema Repetitivo 974 SIRDR 3 STJ.pdf/exemplo-peticao.pdf
@file_name = peticao-inicial.pdf
@petition_id = 01KNFAPYAQC9NYFD3NYQC2GSXS

### Criar petição (CreatePetitionController)
POST {{url}}/petitions
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "analysis_id": "{{analysis_id}}",
  "uploaded_at": "{{uploaded_at}}",
  "document": {
    "file_path": "{{file_path}}",
    "name": "{{file_name}}"
  }
}

### Gerar resumo da peticao (SummarizePetitionController)
POST {{url}}/petitions/{{petition_id}}/summary
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

