@url = {{BASE_URL}}/intake
@precedent_court = STJ
@precedent_kind = RR
@precedent_number = 974

### Obter precedente (GetPrecedentController)
GET {{url}}/precedents?court={{precedent_court}}&kind={{precedent_kind}}&number={{precedent_number}}
Authorization: Bearer {{ACCESS_TOKEN}}

### Adicionar precedente a análise (AddAnalysisPrecedentByIdentifierController)
POST {{url}}/analyses/01KRKEW0MNECWS8AQAJGFGZPC0/precedents
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "court": "{{precedent_court}}",
  "kind": "{{precedent_kind}}",
  "number": {{precedent_number}}
}
